# Generated by Django 4.0.4 on 2022-06-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(0, 'PAQ Skin'), (1, 'PAQ Ankle'), (2, 'PAQ Back'), (3, 'PAQ Nerve'), (4, 'PAQ Chronic Fatigue Syndrome'), (5, 'PAQ Sinusitis'), (6, 'PAQ Diabetes'), (7, 'PAQ ED'), (8, 'PAQ Elbow'), (9, 'PAQ Fibromyalgia'), (10, 'PAQ Feet'), (11, 'PAQ Gallbladder'), (12, 'PAQ GERD'), (13, 'PAQ Gout & Arthritis'), (14, 'PAQ Hand and Finger'), (15, 'PAQ Headaches'), (16, 'PAQ Heart'), (17, 'PAQ Rectum and Anus'), (18, 'PAQ Hepatitis C'), (19, 'PAQ Hip'), (20, 'PAQ Hypertension'), (21, 'PAQ Gynecological'), (22, 'PAQ IBS'), (23, 'PAQ Wrist'), (24, 'PAQ Inguinal Hernia'), (25, 'PAQ Intestine Fistula'), (26, 'PAQ Voiding Dysfunction to Include Prostate Condition'), (27, 'PAQ Knee'), (28, 'PAQ Large Intestine'), (29, 'PAQ Respiratory'), (30, 'PAQ Mental'), (31, 'PAQ MS'), (32, 'PAQ Neck'), (33, 'PAQ Epilepsy'), (34, 'PAQ Shoulder'), (35, 'PAQ Sleep Apnea'), (36, 'PAQ Vein and Artery'), (37, 'PAQ Ventral Hernia')], max_length=50, unique=True)),
                ('paq_record', models.CharField(default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
